name: Build GBC docker image

on:
  push:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ghcr.io/gnosischain/gbc-nimbus

jobs:
  build-amd64:
    name: Linux AMD64 release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: status-im/nimbus-eth2
          ref: c29aa9d8465a536ba4c426ceff0b679dc56e4db5
      - name: Checkout configs
        uses: actions/checkout@v2
        with:
          path: launch
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build binary
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: dist:latest
          file: launch/build/docker/dist/Dockerfile.amd64
          context: launch/build/docker/dist
          outputs: type=docker
          build-args: |
            USER_ID=1000
            GROUP_ID=1000
      - name: Build dist
        run: docker run --privileged -u 0:0 --rm -v ${{ github.workspace }}:/home/user/nimbus-eth2 dist:latest
      - name: Prepare docker builder
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          file: launch/build/docker/dist/binaries/Dockerfile.amd64
          context: .
      - name: Upload archive artefact
        uses: actions/upload-artifact@v2
        with:
          name: Linux_amd64_archive
          path: ./dist/${{ steps.make_dist.outputs.archive }}
      - name: Upload checksum artefact
        uses: actions/upload-artifact@v2
        with:
          name: Linux_amd64_checksum
          path: ./dist/${{ steps.make_dist.outputs.archive_dir }}/build/nimbus_beacon_node_gnosis.sha512sum
